env:
  es2020: true
  browser: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
parserOptions:
  sourceType: module
settings:
  react:
    version: detect
rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
