name: Check & Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build_img:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Check & Build
        uses: docker/build-push-action@v5.1.0
